name: Application CI
on: [push, pull_request]
jobs:
  pipeline:
    name: powierzenia pipeline
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, '[ci skip]') && !contains(github.event.head_commit.message, '[skip ci]')"
    timeout-minutes: 40
    env:
      NODE_VERSION: 12.13.1
      SPRING_OUTPUT_ANSI_ENABLED: DETECT
      SPRING_JPA_SHOW_SQL: false
      JHI_DISABLE_WEBPACK_LOGS: true
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: 12.13.1
      - uses: actions/setup-java@v1
        with:
          java-version: '11.x'
      - name: Install node.js packages
        run: npm install
      - name: Run backend test
        run: |
          chmod +x gradlew
          ./gradlew clean test integrationTest -x webpack
      - name: Run frontend test
        run: npm run test-ci
      - name: Package application
        run: ./gradlew bootJar -Pprod -x test -x integrationTest
